name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  frontend-checks:
    name: Test Angular workspace
    runs-on: centeva-strix
    permissions:
      contents: read
      packages: write
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v1
        with:
          node-version: 24.x
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup frontend
        run: |
          npm ci --cache ~/.npm
      - name: Lint
        run: npx ng lint
      - name: Build library
        run: npx ng build angular-mentions
      - name: Build demo app
        run: npx ng build demo-app
      - name: Test
        run: |
          npx ng test angular-mentions --watch=false
          npx ng test demo-app --watch=false
